//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tsystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Registered_in_the_course
    {
        public int User_ID { get; set; }
        public int Course_ID { get; set; }
        public string Attendance_Status { get; set; }
        public string Evaluation_Status { get; set; }
        public string Certificate_Status { get; set; }
    
        public virtual CourseSchedule CourseSchedule { get; set; }
        public virtual User User { get; set; }
    }
}
