//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tsystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Support_Ticket
    {
        public int Ticket_No { get; set; }
        public string Title { get; set; }
        public string Content { get; set; }
        public int User_ID { get; set; }
        public System.DateTime Date { get; set; }
        public string Status { get; set; }
    
        public virtual User User { get; set; }
    }
}
