//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tsystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public User()
        {
            this.Registered_in_the_course = new HashSet<Registered_in_the_course>();
            this.Support_Tickets = new HashSet<Support_Ticket>();
        }
    
        public int User_ID { get; set; }
        public string Ar_Name { get; set; }
        public string En_name { get; set; }
        public string email { get; set; }
        public string mobile { get; set; }
        public Nullable<int> Role_ID { get; set; }
        public string Degree { get; set; }
        public string gender { get; set; }
        public string Section { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Registered_in_the_course> Registered_in_the_course { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Support_Ticket> Support_Tickets { get; set; }
        public virtual User_Role User_Role { get; set; }
    }
}
